package com.thomas.greenconverter.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.thomas.greenconverter.User;
import com.thomas.greenconverter.User_Converter.Converter;
import com.thomas.greenconverter.User_ListConverter.ListConverter;
import java.util.List;

import com.thomas.greenconverter.UserEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_ENTITY".
*/
public class UserEntityDao extends AbstractDao<UserEntity, Long> {

    public static final String TABLENAME = "USER_ENTITY";

    /**
     * Properties of entity UserEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, long.class, "id", true, "_id");
        public final static Property MUser = new Property(1, String.class, "mUser", false, "M_USER");
        public final static Property MUsers = new Property(2, String.class, "mUsers", false, "M_USERS");
    }

    private final Converter mUserConverter = new Converter();
    private final ListConverter mUsersConverter = new ListConverter();

    public UserEntityDao(DaoConfig config) {
        super(config);
    }
    
    public UserEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_ENTITY\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL ," + // 0: id
                "\"M_USER\" TEXT," + // 1: mUser
                "\"M_USERS\" TEXT);"); // 2: mUsers
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        User mUser = entity.getMUser();
        if (mUser != null) {
            stmt.bindString(2, mUserConverter.convertToDatabaseValue(mUser));
        }
 
        List mUsers = entity.getMUsers();
        if (mUsers != null) {
            stmt.bindString(3, mUsersConverter.convertToDatabaseValue(mUsers));
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserEntity entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getId());
 
        User mUser = entity.getMUser();
        if (mUser != null) {
            stmt.bindString(2, mUserConverter.convertToDatabaseValue(mUser));
        }
 
        List mUsers = entity.getMUsers();
        if (mUsers != null) {
            stmt.bindString(3, mUsersConverter.convertToDatabaseValue(mUsers));
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.getLong(offset + 0);
    }    

    @Override
    public UserEntity readEntity(Cursor cursor, int offset) {
        UserEntity entity = new UserEntity( //
            cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : mUserConverter.convertToEntityProperty(cursor.getString(offset + 1)), // mUser
            cursor.isNull(offset + 2) ? null : mUsersConverter.convertToEntityProperty(cursor.getString(offset + 2)) // mUsers
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserEntity entity, int offset) {
        entity.setId(cursor.getLong(offset + 0));
        entity.setMUser(cursor.isNull(offset + 1) ? null : mUserConverter.convertToEntityProperty(cursor.getString(offset + 1)));
        entity.setMUsers(cursor.isNull(offset + 2) ? null : mUsersConverter.convertToEntityProperty(cursor.getString(offset + 2)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserEntity entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserEntity entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserEntity entity) {
        throw new UnsupportedOperationException("Unsupported for entities with a non-null key");
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
